---
# Config file for automatic testing at travis-ci.org
# http://travis-ci.org/#!/ipython/ipython
language: python

python:
    - 3.8
    - 3.7
    - 3.6

sudo: false

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH

before_install:
  - pip install --upgrade setuptools wheel nose coverage codecov
  - |
    # install Python on macOS
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      env | sort
      if ! which python$TRAVIS_PYTHON_VERSION; then
        HOMEBREW_NO_AUTO_UPDATE=1 brew tap minrk/homebrew-python-frameworks
        HOMEBREW_NO_AUTO_UPDATE=1 brew cask install python-framework-${TRAVIS_PYTHON_VERSION/./}
      fi
        python3 -m pip install virtualenv
        python3 -m virtualenv -p $(which python$TRAVIS_PYTHON_VERSION) ~/travis-env
        source ~/travis-env/bin/activate
    fi
    if [[ $GROUP == docs ]]; then
      pip install -r docs/doc-requirements.txt
      pip install --upgrade pytest
    fi

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows

    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS

    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# - pip3 install -U -r requirements.txt -e .

install:
  - pip3 install pip --upgrade
  # - pip3 install setuptools --upgrade
  # - pip3 install -e file://$PWD#egg=ipython[test] --upgrade
  - pip3 install trio curio --upgrade --upgrade-strategy eager
  # - pip3 install 'pytest<4' matplotlib
  - pip3 install codecov check-manifest --upgrade
  - pip3 install -U -e . -r requirements.txt


# command to run tests, e.g. python setup.py test
# script: nosetests
script:
  # - check-manifest
  # - |
  #   if [[ "$TRAVIS_PYTHON_VERSION" == "nightly" ]]; then
  #      # on nightly fake parso known the grammar
  #      cp /home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/parso/python/grammar37.txt /home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/parso/python/grammar38.txt
    # fi
  - cd /tmp && iptest --coverage xml && cd -
  - pytest IPython
  # On the latest Python (on Linux) only, make sure that the docs build.
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip3 install -U -r docs/requirements.txt
      python3 tools/fixup_whats_new_pr.py
      # make -C docs/ html SPHINXOPTS="-W"
      sphinx-build -c docs/source -W --keep-going docs/source docs/build
    fi

after_success:
  - cp /tmp/ipy_coverage.xml ./
  - cp /tmp/.coverage ./
  - codecov

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.8-dev"
      dist: xenial
      sudo: true
    - python: "3.7-dev"
      dist: xenial
      sudo: true
    - python: "nightly"
      dist: xenial
      sudo: true
    - os: osx
      language: generic
      python: 3.6
      env: TRAVIS_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      python: 3.7
      env: TRAVIS_PYTHON_VERSION=3.7
  allow_failures:
    - python: nightly

before_deploy:
  - rm -rf dist/
  - python setup.py sdist
  - python setup.py bdist_wheel

deploy:
  provider: releases
  api_key:
    secure: Y/Ae9tYs5aoBU8bDjN2YrwGG6tCbezj/h3Lcmtx8HQavSbBgXnhnZVRb2snOKD7auqnqjfT/7QMm4ZyKvaOEgyggGktKqEKYHC8KOZ7yp8I5/UMDtk6j9TnXpSqqBxPiud4MDV76SfRYEQiaDoG4tGGvSfPJ9KcNjKrNvSyyxns=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: ipython/ipython
    all_branches: true  # Backports are released from e.g. 5.x branch
    tags: true
    python: 3.7  # Any version should work, but we only need one
    condition: $TRAVIS_OS_NAME = "linux"

...
