---
# Config file for automatic testing at travis-ci.org
# http://travis-ci.org/#!/ipython/ipython
language: python # this works for Linux but is an error on macOS or Windows
os: linux
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
    - LANG=C.UTF-8
group: edge # ?
cache:
  - pip

install:
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
    # this command works on linux but not on mac because of permission issues.

        if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
            pip3 install --upgrade pip -r requirements.txt -e .
        else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda config --add channels conda-forge
            # Useful for debugging any issues with conda
            conda info -a
            conda create -q -n test-environment python=$CONDA_PY ipython pytest matplotlib setuptools wheel nose coverage codecov pyqt sphinx testpath flake8 flake8-rst
            source activate test-environment
        fi
    else
        python -m pip install -U pip -r requirements.txt -e .
    fi

script:
  - iptest --coverage xml
  - pytest IPython
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install -U -r docs/requirements.txt
      sphinx-build -c docs/source -W --keep-going docs/source docs/build
    fi

after_success:
  - codecov

matrix:
  include:
    - python: "3.7"
      name: "Python 3.7.0 on Bionic Linux"
      dist: "bionic" # because now we get py3.6 and py3.7 for free
      before_install:
        - python setup.py build
        - |
          if [[ $GROUP == docs ]]; then
            pip install -r docs/doc-requirements.txt
            pip install --upgrade pytest
          fi
    - python: "3.8-dev"
      dist: "bionic"
      name: "Python 3.8-dev on Bionic Linux"
      before_install:
        - python setup.py build
        - |
          if [[ $GROUP == docs ]]; then
            pip install -r docs/doc-requirements.txt
            pip install --upgrade pytest
          fi
    - python: "3.6"
      dist: "bionic"
      name: "Python 3.6 on Bionic Linux"
      before_install:
        - python setup.py build
        - |
          if [[ $GROUP == docs ]]; then
            pip install -r docs/doc-requirements.txt
            pip install --upgrade pytest
          fi
    - python: "nightly"
      dist: "bionic"
    - os: osx
      # language: generic
      language: shell # 'language: python' is an error on Travis CI macOS
      python: 3.6
      osx_image: xcode11.2 # Python 3.7.4 running on macOS 10.14.4
      env: TRAVIS_PYTHON_VERSION=3.6
      name: "Python 3.6 on macOS - Conda"
      before_install:
        - python setup.py build
    - os: osx
      python: 3.7
      env: TRAVIS_PYTHON_VERSION=3.7
      osx_image: xcode11.2 # Python 3.7.4 running on macOS 10.14.4
      language: shell # 'language: python' is an error on Travis CI macOS
      name: "Python 3.7 on macOS - Conda"
      before_install:
        - python setup.py build
    - os: windows
      language: shell
      env:
        - TRAVIS_PYTHON_VERSION=3.8
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      python: 3.8
      name: "Python 3.8.0 on Windows"
      before_install:
        - choco install python --version 3.8.0
        - python setup.py build
        - python -m pip install --upgrade pip -e . -r requirements.txt
  allow_failures:
    - python: nightly

before_deploy:
  - rm -rf dist/
  - python setup.py sdist
  - python setup.py bdist_wheel

deploy:
  provider: releases
  token:
    secure: Y/Ae9tYs5aoBU8bDjN2YrwGG6tCbezj/h3Lcmtx8HQavSbBgXnhnZVRb2snOKD7auqnqjfT/7QMm4ZyKvaOEgyggGktKqEKYHC8KOZ7yp8I5/UMDtk6j9TnXpSqqBxPiud4MDV76SfRYEQiaDoG4tGGvSfPJ9KcNjKrNvSyyxns=
  file: dist/*
  file_glob: true
  cleanup: true
  on:
    repo: ipython/ipython
    all_branches: true # Backports are released from e.g. 5.x branch
    tags: true
    python: 3.7 # Any version should work, but we only need one
    condition: $TRAVIS_OS_NAME = "linux"
