---
# Config file for automatic testing at travis-ci.org
# http://travis-ci.org/#!/ipython/ipython
language: python            # this works for Linux but is an error on macOS or Windows
os: linux
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
    - LANG=C.UTF-8
group: edge   # ?
cache:
  - pip
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      dist: "bionic"        # because now we get py3.6 and py3.7 for free
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - python setup.py build
        - |
          if [[ $GROUP == docs ]]; then
            pip install -r docs/doc-requirements.txt
            pip install --upgrade pytest
          fi
    - name: "Python 3.7.4 on macOS"
      os: osx
      python: 3.7
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip install --upgrade setuptools wheel nose coverage codecov
        - |
          if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            env | sort
            if ! which python$TRAVIS_PYTHON_VERSION; then
              HOMEBREW_NO_AUTO_UPDATE=1 brew tap minrk/homebrew-python-frameworks
              HOMEBREW_NO_AUTO_UPDATE=1 brew cask install python-framework-${TRAVIS_PYTHON_VERSION/./}
            fi
              python3 -m pip install virtualenv
              python3 -m virtualenv -p $(which python$TRAVIS_PYTHON_VERSION) ~/travis-env
              source ~/travis-env/bin/activate
          fi
          if [[ $GROUP == docs ]]; then
            pip install -r docs/doc-requirements.txt
            pip install --upgrade pytest
          fi
          - pip3 install -U -e . -r requirements.txt
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      python: 3.8
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.0
        - python setup.py build
        - python -m pip install --upgrade pip -e . -r requirements.txt

install:
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
    # forgot the user ughhhh
    # Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
    # Guys they gave me a permissions error AND an error about using --user in a venv
    # I'm turning sudo on
    pip3 install --upgrade pip -r requirements.txt -e .
    # all three OSes agree about 'pip3'
    # no they don't travis you lied to me!
    else
    python -m pip install -U pip -r requirements.txt -e .
    fi


script:
  - iptest --coverage xml
  - pytest IPython
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install -U -r docs/requirements.txt
      sphinx-build -c docs/source -W --keep-going docs/source docs/build
    fi

after_success:
  - codecov

matrix:
  include:
    - python: "3.7"
      dist: "bionic"
      sudo: true
    - python: "3.8-dev"
      dist: "bionic"
      sudo: true
    - python: "3.7-dev"
      dist: "bionic"
      sudo: true
    - python: "nightly"
      dist: "bionic"
      sudo: true
    - os: osx
      language: generic
      python: 3.6
      env: TRAVIS_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      python: 3.7
      env: TRAVIS_PYTHON_VERSION=3.7
    - os: windows
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.8
      python: 3.8
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.0
        - python setup.py build
        - python -m pip install --upgrade pip -e . -r requirements.txt
  allow_failures:
    - python: nightly

before_deploy:
  - rm -rf dist/
  - python setup.py sdist
  - python setup.py bdist_wheel

deploy:
  provider: releases
  api_key:
    secure: Y/Ae9tYs5aoBU8bDjN2YrwGG6tCbezj/h3Lcmtx8HQavSbBgXnhnZVRb2snOKD7auqnqjfT/7QMm4ZyKvaOEgyggGktKqEKYHC8KOZ7yp8I5/UMDtk6j9TnXpSqqBxPiud4MDV76SfRYEQiaDoG4tGGvSfPJ9KcNjKrNvSyyxns=
  file: dist/*
  file_glob: true
  cleanup: true
  on:
    repo: ipython/ipython
    all_branches: true  # Backports are released from e.g. 5.x branch
    tags: true
    python: 3.7  # Any version should work, but we only need one
    condition: $TRAVIS_OS_NAME = "linux"

...
