{% set name = "IPython" %}
{% set version = "7.9.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dfd303b270b7b5232b3d08bd30ec6fd685d8a58cabd54055e3d69d8f029f7280

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - IPython
    - IPython.core
    - IPython.core.magics
    - IPython.core.tests
    - IPython.extensions
    - IPython.extensions.tests
    - IPython.external
    - IPython.external.decorators
    - IPython.kernel
    - IPython.lib
    - IPython.lib.tests
    - IPython.sphinxext
    - IPython.terminal
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.tests
    - IPython.utils
    - IPython.utils.tests

about:
  home: "https://ipython.org"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "IPython: Productive Interactive Computing"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
